import type {
  BanditAdvisorySection,
} from "./qa.types";

// Default advisory content for v13 checklist
export const defaultAdvisoryV13: BanditAdvisorySection = {
  questions: [
    {
      id: "mission-control-primary-role",
      prompt: "Should Mission Control become the primary left-dock cockpit, or remain mostly QA-focused?",
      context: "Mission Control currently serves as QA panel. Consider whether it should expand to broader control plane operations.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "next-major-feature-priority",
      prompt: "Should the next major feature be Graph Inspector v0 or QA Contract Ledger v0?",
      context: "Graph Inspector would show read-only node/edge details. QA Contract Ledger would make accepted QA reports visible as baseline history.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "graph-selection-read-only",
      prompt: "Should graph selection details stay read-only for now?",
      context: "Currently selection details are displayed but not editable. Consider whether editing is needed or if read-only is sufficient.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "experimental-mode-gate",
      prompt: "Should future visual features require a separate 'experimental mode' toggle?",
      context: "This would protect unfinished/future controls from being accidentally enabled in production workflows.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "qa-baseline-ledger",
      prompt: "Should accepted QA reports become a visible baseline ledger?",
      context: "This would create a history of accepted baselines for reference and regression detection.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "docs-registry-relationship",
      prompt: "Should docs and runtime contract registry be kept separate, or should one generate the other later?",
      context: "Currently docs are manual markdown and registry is TypeScript. Consider whether to automate synchronization.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "playwright-coverage-priority",
      prompt: "Should Playwright coverage prioritize graph behavior or Mission Control workflows next?",
      context: "Graph behavior tests verify rendering and interaction. Mission Control workflow tests verify QA submission and history.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "theme-customization-preset-only",
      prompt: "Should theme customization remain preset-only until graph intelligence stabilizes?",
      context: "Custom theme editor is planned but could be deferred until graph intelligence features are more stable.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "control-plane-organization",
      prompt: "Should Control Plane settings be reorganized by task, by system, or by visual layer?",
      context: "Current organization is by category. Consider whether task-based, system-based, or visual-layer-based organization would be more intuitive.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
    {
      id: "bandit-proposal-section",
      prompt: "Should Bandit include a proposal section at the end of every major pass?",
      context: "This would make Bandit's thinking more visible and provide structured proposal review.",
      responseType: "choice",
      userResponse: "",
      status: "unanswered",
    },
  ],
  proposals: [
    {
      id: "graph-inspector-v0",
      title: "Graph Inspector v0",
      summary: "Read-only selected node/edge details panel showing metadata and relationships.",
      rationale: "Users need to inspect node and edge properties without editing them. This provides a read-only view for investigation.",
      risk: "low",
      recommendedNextAction: "Add as next major feature after advisory channel stabilizes.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "qa-contract-ledger-v0",
      title: "QA Contract Ledger v0",
      summary: "Accepted QA reports as visible baseline history with diff comparison.",
      rationale: "Track accepted baselines over time to detect regressions and understand evolution of requirements.",
      risk: "low",
      recommendedNextAction: "Add after Graph Inspector v0 or in parallel.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "experimental-mode-gate",
      title: "Experimental Mode Gate",
      summary: "Protect unfinished/future controls with a separate experimental mode toggle.",
      rationale: "Prevent accidental enabling of incomplete features in production workflows.",
      risk: "low",
      recommendedNextAction: "Implement when first experimental control is added.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "handleset-drift-checker",
      title: "Handleset Drift Checker",
      summary: "Compare docs/registry/runtime coverage to detect drift between documentation and implementation.",
      rationale: "Ensure documentation stays in sync with actual runtime behavior to prevent confusion.",
      risk: "medium",
      recommendedNextAction: "Add as utility after contract registry stabilizes.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "theme-token-coverage-test",
      title: "Theme Token Coverage Test",
      summary: "Stronger automated coverage for all built-in theme tokens.",
      rationale: "Ensure all theme presets render correctly and tokens are applied consistently.",
      risk: "low",
      recommendedNextAction: "Expand existing theme tests to cover all token combinations.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "mission-control-report-export",
      title: "Mission Control Report Export",
      summary: "Copy/download QA reports cleanly in multiple formats (markdown, JSON).",
      rationale: "Enable easier sharing and archival of QA reports for documentation and handoff.",
      risk: "low",
      recommendedNextAction: "Add export options to existing copy functionality.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "graph-search-filter-v0",
      title: "Graph Search / Filter v0",
      summary: "Find nodes by name, type, or property in the graph.",
      rationale: "Large graphs become difficult to navigate without search/filter capabilities.",
      risk: "medium",
      recommendedNextAction: "Implement basic search after graph rendering stabilizes.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "source-link-readiness-audit",
      title: "Source Link Readiness Audit",
      summary: "Prepare for future open-in-editor links by auditing source file references.",
      rationale: "Before adding source file links, ensure all references are accurate and files exist.",
      risk: "low",
      recommendedNextAction: "Audit contract registry source file paths.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "label-preset-system",
      title: "Label Preset System",
      summary: "Save label visibility combinations as presets for quick switching.",
      rationale: "Users often switch between different label configurations (debug mode vs presentation mode).",
      risk: "low",
      recommendedNextAction: "Add after label controls stabilize.",
      userDecision: "unreviewed",
      userNotes: "",
    },
    {
      id: "layout-lens-presets",
      title: "Layout Lens Presets",
      summary: "Switch between exploration views (constellation, district, pipeline, etc.).",
      rationale: "Different graph layouts are useful for different exploration tasks. Presets enable quick switching.",
      risk: "medium",
      recommendedNextAction: "Implement after basic layout engine stabilizes.",
      userDecision: "unreviewed",
      userNotes: "",
    },
  ],
  backlog: [
    {
      rank: 1,
      title: "Graph Inspector v0",
      whyItMatters: "Users need to inspect node/edge details without editing. Foundation for future editing capabilities.",
      suggestedFutureBite: "Graph Inspector v0",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 2,
      title: "Experimental Mode Gate",
      whyItMatters: "Protect unfinished features from accidental production use.",
      suggestedFutureBite: "Experimental Mode Gate",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 3,
      title: "QA Contract Ledger v0",
      whyItMatters: "Track accepted baselines for regression detection and historical reference.",
      suggestedFutureBite: "QA Contract Ledger v0",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 4,
      title: "Handleset Drift Checker",
      whyItMatters: "Ensure docs/registry/runtime stay in sync to prevent confusion.",
      suggestedFutureBite: "Handleset Drift Checker",
      risk: "medium",
      status: "candidate",
    },
    {
      rank: 5,
      title: "Source Link Readiness Audit",
      whyItMatters: "Prepare for future open-in-editor links by verifying source references.",
      suggestedFutureBite: "Source Link Readiness Audit",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 6,
      title: "Theme Token Coverage Test",
      whyItMatters: "Ensure all theme presets render correctly across all tokens.",
      suggestedFutureBite: "Theme Token Coverage Test",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 7,
      title: "Mission Control Report Export",
      whyItMatters: "Enable easier sharing and archival of QA reports.",
      suggestedFutureBite: "Mission Control Report Export",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 8,
      title: "Graph Search / Filter v0",
      whyItMatters: "Large graphs need search/filter for navigation.",
      suggestedFutureBite: "Graph Search / Filter v0",
      risk: "medium",
      status: "candidate",
    },
    {
      rank: 9,
      title: "Label Preset System",
      whyItMatters: "Quick switching between label configurations for different workflows.",
      suggestedFutureBite: "Label Preset System",
      risk: "low",
      status: "candidate",
    },
    {
      rank: 10,
      title: "Layout Lens Presets",
      whyItMatters: "Different layouts for different exploration tasks.",
      suggestedFutureBite: "Layout Lens Presets",
      risk: "medium",
      status: "candidate",
    },
  ],
};
