// SPDX-License-Identifier: Apache-2.0
import type { QaCheckDefinition } from "./qa.types";

export const FEEDBACK_CHECKLIST_KEY = "feedback-v1";

export const FEEDBACK_CHECKS: QaCheckDefinition[] = [
  {
    id: "feedback-graph-load",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Did the graph load correctly when you opened LumaWeave?",
    expected: "Graph rendered with nodes and edges visible",
    qaVersion: 1,
    active: true,
    steps: ["Open LumaWeave", "Confirm graph appears in viewport"],
    required: false,
  },
  {
    id: "feedback-tiles-discoverable",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Were the tiles (Physics, Appearance, etc.) easy to find and use?",
    expected: "Tiles visible on app load; chrome readable; controls work as expected",
    qaVersion: 1,
    active: true,
    steps: ["Look at right edge of viewport", "Try interacting with each visible tile"],
    required: false,
  },
  {
    id: "feedback-theme-switch",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Did switching themes work smoothly?",
    expected: "Theme dropdown changes graph colors with smooth crossfade",
    qaVersion: 1,
    active: true,
    steps: ["Click theme dropdown in topbar", "Select a different theme", "Observe transition"],
    required: false,
  },
  {
    id: "feedback-command-palette",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Did the command palette (Ctrl+K) work as expected?",
    expected: "Palette opens, search works, commands fire when selected",
    qaVersion: 1,
    active: true,
    steps: ["Press Ctrl+K", "Type a command name", "Press Enter to fire"],
    required: false,
  },
  {
    id: "feedback-performance",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Was the app performance acceptable during your session?",
    expected: "Smooth interactions, no noticeable lag on typical actions",
    qaVersion: 1,
    active: true,
    steps: ["Recall your session", "Note any specific moments of lag or jank"],
    required: false,
  },
  {
    id: "feedback-most-useful",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "What was the most useful feature you discovered?",
    expected: "User reports a specific feature they found valuable",
    qaVersion: 1,
    active: true,
    steps: ["Reflect on your session", "Add a note describing the feature"],
    required: false,
  },
  {
    id: "feedback-most-confusing",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "What was the most confusing aspect?",
    expected: "User reports a specific confusing aspect with context",
    qaVersion: 1,
    active: true,
    steps: ["Reflect on your session", "Add a note describing the confusion"],
    required: false,
  },
  {
    id: "feedback-suggestion",
    featureId: "feedback-v1",
    featureName: "Early User Feedback",
    qaKey: "feedback-v1",
    title: "Anything you'd like to see added or changed?",
    expected: "User submits suggestion with as much detail as they'd like",
    qaVersion: 1,
    active: true,
    steps: ["Add a note describing the suggestion"],
    required: false,
  },
];
